import { db } from "@workspace/db";
import { quizQuestionsTable } from "@workspace/db";

const questions: { moduleId: number; question: string; options: string[]; correctOption: number; order: number }[] = [

  // ─── Module 9: PPE & First Aid ───────────────────────────────────────────────
  { moduleId: 9, order: 1, question: "What is the PRIMARY purpose of chainsaw protective trousers?", options: ["Provide warmth in cold conditions", "Stop or slow a chainsaw chain on contact with the leg", "Improve operator visibility", "Protect against thorns and branches only"], correctOption: 1 },
  { moduleId: 9, order: 2, question: "What is the FIRST action to take when a chainsaw operator sustains a deep cut?", options: ["Apply direct pressure to control bleeding and call 999", "Remove the chainsaw chain from the wound immediately", "Give the casualty food and water", "Continue working and treat the injury later"], correctOption: 0 },
  { moduleId: 9, order: 3, question: "Which standard governs chainsaw protective clothing in the UK?", options: ["BS EN 381", "BS EN 397", "BS EN 471", "BS EN 166"], correctOption: 0 },
  { moduleId: 9, order: 4, question: "How frequently must chainsaw PPE be inspected for damage?", options: ["Once per year", "Once per month", "Before every use", "Only when it visibly looks worn"], correctOption: 2 },

  // ─── Module 10: 5 Steps To Risk Assessment ───────────────────────────────────
  { moduleId: 10, order: 1, question: "What is the FIRST step in the 5-step risk assessment process?", options: ["Record your findings", "Identify the hazards", "Evaluate the risks", "Implement control measures"], correctOption: 1 },
  { moduleId: 10, order: 2, question: "Under the Management of Health and Safety at Work Regulations 1999, who must carry out a risk assessment?", options: ["The Health and Safety Executive", "The local authority", "Employers and self-employed persons", "Only qualified safety officers"], correctOption: 2 },
  { moduleId: 10, order: 3, question: "A risk assessment must be reviewed when:", options: ["A new calendar year begins", "Working conditions change significantly", "A manager verbally requests it", "Staff turnover occurs"], correctOption: 1 },
  { moduleId: 10, order: 4, question: "In a risk assessment, what does 'risk' specifically mean?", options: ["The likelihood that harm will occur from a hazard", "The physical object that could cause harm", "The financial cost of an accident", "The legal penalties for non-compliance"], correctOption: 0 },

  // ─── Module 12: Emergency Planning Information ───────────────────────────────
  { moduleId: 12, order: 1, question: "Before starting chainsaw work, what emergency information must be established?", options: ["The nearest fuel station", "The nearest hardware store", "The site manager's home address", "The location of emergency services and a means to contact them"], correctOption: 3 },
  { moduleId: 12, order: 2, question: "What is the recommended approach for lone workers operating a chainsaw?", options: ["Check in every 4 hours", "Check in every 8 hours", "Check in at regular agreed intervals (e.g. every 30 minutes)", "Check in once per day"], correctOption: 2 },
  { moduleId: 12, order: 3, question: "An emergency action card should include:", options: ["Personal social media contacts", "Equipment hire costs", "Site location, grid reference, and emergency service numbers", "Manufacturer warranty information"], correctOption: 2 },
  { moduleId: 12, order: 4, question: "What does 'point of work risk assessment' mean?", options: ["An assessment carried out at the actual working location before starting work", "An assessment completed in the office before site arrival", "A financial assessment of the job", "An assessment completed after work is finished"], correctOption: 0 },

  // ─── Module 13: Law & Legislation ─────────────────────────────────────────────
  { moduleId: 13, order: 1, question: "Which legislation requires work equipment to be safe and suitable for its intended use?", options: ["Health and Safety at Work Act 1974", "Workplace (Health, Safety and Welfare) Regulations 1992", "Provision and Use of Work Equipment Regulations 1998 (PUWER)", "Manual Handling Operations Regulations 1992"], correctOption: 2 },
  { moduleId: 13, order: 2, question: "Who is the primary enforcing authority for health and safety in UK forestry and arboriculture?", options: ["The local council", "The Forestry Commission", "The Environment Agency", "The Health and Safety Executive (HSE)"], correctOption: 3 },
  { moduleId: 13, order: 3, question: "The Health and Safety at Work Act 1974 places a duty on employees to:", options: ["Take reasonable care for their own and others' health and safety", "Purchase their own PPE", "Report all incidents to the police", "Only follow instructions given in writing"], correctOption: 0 },
  { moduleId: 13, order: 4, question: "PUWER stands for:", options: ["Personal Use of Work Equipment Regulations", "Protection and Upkeep of Work Equipment Regulations", "Provision and Use of Work Equipment Regulations", "Prevention of Unsafe Work Equipment Risks"], correctOption: 2 },

  // ─── Module 14: Chainsaw Safety Features ─────────────────────────────────────
  { moduleId: 14, order: 1, question: "What is the primary function of the chain brake?", options: ["Stop the chain rotating rapidly in the event of kickback", "Sharpen the chain automatically", "Prevent the engine from starting accidentally", "Control engine speed at idle"], correctOption: 0 },
  { moduleId: 14, order: 2, question: "The chain catcher on a chainsaw is designed to:", options: ["Collect sawdust", "Hold the chain during sharpening", "Reduce chain noise", "Protect the operator if the chain breaks or derails"], correctOption: 3 },
  { moduleId: 14, order: 3, question: "What is the purpose of the anti-vibration (AV) system on a chainsaw?", options: ["Reduce engine noise emissions", "Prevent chain derailment", "Reduce vibration transmitted from the saw to the operator's hands", "Improve fuel efficiency"], correctOption: 2 },
  { moduleId: 14, order: 4, question: "The front hand guard on a chainsaw:", options: ["Protects the operator's hand from the chain and activates the chain brake", "Acts as a handhold during transport", "Supports the weight of the saw", "Prevents fuel from splashing the operator"], correctOption: 0 },

  // ─── Module 40: Battery Chainsaws ─────────────────────────────────────────────
  { moduleId: 40, order: 1, question: "What is the primary advantage of a battery-powered chainsaw over a petrol chainsaw?", options: ["Greater cutting power for heavy timber", "Longer run time without stopping", "Cheaper to purchase initially", "Zero exhaust emissions and lower noise levels, making it suitable for indoor or urban environments"], correctOption: 3 },
  { moduleId: 40, order: 2, question: "How should a lithium-ion chainsaw battery be stored when not in use for an extended period?", options: ["Fully discharged in a sealed plastic bag", "Fully charged in direct sunlight to maintain cell voltage", "At approximately 40–60% charge in a cool, dry place away from extreme temperatures", "Submerged in oil to prevent corrosion"], correctOption: 2 },
  { moduleId: 40, order: 3, question: "Which of the following is a key limitation of battery-powered chainsaws compared to petrol models?", options: ["They cannot be fitted with a chain brake", "They require more PPE than petrol chainsaws", "Run time is limited by battery capacity, requiring charged spare batteries for prolonged use", "They are heavier due to the engine block"], correctOption: 2 },
  { moduleId: 40, order: 4, question: "What safety check is unique to a battery-powered chainsaw before use?", options: ["Verify the battery charge level and inspect the battery and terminals for damage before fitting", "Check the spark plug gap", "Check the fuel-to-oil mix ratio", "Test the recoil starter mechanism"], correctOption: 0 },

  // ─── Module 15: Air Filter ────────────────────────────────────────────────────
  { moduleId: 15, order: 1, question: "Why is it critical to clean or replace a blocked chainsaw air filter?", options: ["A blocked filter makes the saw louder", "A blocked filter improves chain speed", "A blocked filter has no effect on performance", "A blocked filter causes a rich mixture, poor performance and overheating"], correctOption: 3 },
  { moduleId: 15, order: 2, question: "How should a foam air filter be cleaned?", options: ["Washed in warm soapy water, dried fully before re-fitting", "Washed in petrol and left to dry", "Scraped clean with a metal tool", "Replaced immediately without attempting to clean"], correctOption: 0 },
  { moduleId: 15, order: 3, question: "When inspecting the air filter, you should also check:", options: ["The bar sprocket nose", "The spark plug gap only", "The filter housing and gasket for damage or leaks", "The chain tension only"], correctOption: 2 },
  { moduleId: 15, order: 4, question: "Operating with a damaged or missing air filter will most likely cause:", options: ["Improved engine performance", "Lower chain speed only", "Reduced vibration only", "Increased engine wear due to ingested debris"], correctOption: 3 },

  // ─── Module 16: Spark Plug ────────────────────────────────────────────────────
  { moduleId: 16, order: 1, question: "What should you assess when inspecting a chainsaw spark plug?", options: ["Electrode condition, gap, and look for fouling or damage", "Replace it after every use regardless of condition", "Only inspect if the saw fails to start", "Clean it with water and refit"], correctOption: 0 },
  { moduleId: 16, order: 2, question: "A black, sooty spark plug electrode typically indicates:", options: ["A lean fuel mixture (too much air)", "A rich fuel mixture or excess oil in the combustion chamber", "Correct engine operation", "Severe overheating"], correctOption: 1 },
  { moduleId: 16, order: 3, question: "What tool is needed to correctly set the spark plug electrode gap?", options: ["A torque wrench", "A vernier calliper", "A multimeter", "A feeler gauge"], correctOption: 3 },
  { moduleId: 16, order: 4, question: "What is the risk of overtightening a spark plug during installation?", options: ["The plug may fall out during operation", "The engine will run too rich", "The cylinder head threads can be stripped or the plug body cracked", "The chain will derail"], correctOption: 2 },

  // ─── Module 17: Cooling System ────────────────────────────────────────────────
  { moduleId: 17, order: 1, question: "Why must cooling fins on a chainsaw cylinder be kept clean?", options: ["To improve the appearance of the saw", "To reduce chain noise", "To improve fuel efficiency only", "To allow adequate airflow and prevent engine overheating"], correctOption: 3 },
  { moduleId: 17, order: 2, question: "What should be used to clean clogged cooling fins?", options: ["A soft brush or plastic tool to dislodge debris without damaging fins", "A metal scraper", "High-pressure water directly on the engine", "Petrol sprayed directly into the fins"], correctOption: 0 },
  { moduleId: 17, order: 3, question: "Where does cooling air typically enter most chainsaw designs?", options: ["Through the exhaust port", "Through the chain tensioner slot", "Through the flywheel and air intake shroud", "Through the bar mounting holes"], correctOption: 2 },
  { moduleId: 17, order: 4, question: "Operating with blocked cooling fins can result in:", options: ["Better fuel economy", "Increased chain speed", "Reduced vibration levels", "Piston seizure and major engine damage"], correctOption: 3 },

  // ─── Module 18: Exhaust ───────────────────────────────────────────────────────
  { moduleId: 18, order: 1, question: "What hazard does a blocked spark arrestor in the exhaust present?", options: ["Increased fuel consumption only", "Reduced chain speed", "Fire risk from ejected hot carbon particles", "Loss of chain lubrication"], correctOption: 2 },
  { moduleId: 18, order: 2, question: "Signs of a failing chainsaw exhaust system include:", options: ["Quieter engine operation", "Improved fuel economy", "Reduced chain vibration", "Exhaust leaks causing burn risk and increased operator noise exposure"], correctOption: 3 },
  { moduleId: 18, order: 3, question: "When should the spark arrestor be cleaned or replaced?", options: ["Per the manufacturer's schedule or when visibly blocked", "It is a sealed unit and never serviced", "Only when the saw fails to start", "After every single use"], correctOption: 0 },
  { moduleId: 18, order: 4, question: "Chainsaw exhaust fumes are particularly dangerous in enclosed or confined spaces because:", options: ["They are brightly coloured and have a strong smell", "They cause skin irritation only", "Carbon monoxide is colourless and odourless and can reach lethal concentrations", "They corrode metal parts rapidly"], correctOption: 2 },

  // ─── Module 19: Fuel & Oil Filters ───────────────────────────────────────────
  { moduleId: 19, order: 1, question: "What is the purpose of the chainsaw fuel filter?", options: ["To mix fuel and bar oil", "To store reserve fuel", "To heat the fuel before combustion", "To prevent debris entering the fuel system and damaging the carburettor"], correctOption: 3 },
  { moduleId: 19, order: 2, question: "Bar and chain oil should have what key property to be effective?", options: ["Sufficient tackiness to adhere to the chain and bar during operation", "Be very thin to flow freely at all temperatures", "Be identical in specification to engine oil", "Be water-based for environmental compliance"], correctOption: 0 },
  { moduleId: 19, order: 3, question: "A partially blocked fuel filter will typically cause:", options: ["Improved fuel economy", "Overfuelling and a rich mixture", "Fuel starvation, causing the engine to cut out under load", "No noticeable change in performance"], correctOption: 2 },
  { moduleId: 19, order: 4, question: "How often should chainsaw fuel and bar oil filters be inspected?", options: ["Only during the annual service", "Only when a fuel problem is noticed", "Every 1,000 hours of use", "Per the manufacturer's maintenance schedule"], correctOption: 3 },

  // ─── Module 20: Recoil Starter ────────────────────────────────────────────────
  { moduleId: 20, order: 1, question: "What must be confirmed before starting a chainsaw using the recoil starter?", options: ["Chain brake is engaged, saw is secure, and area is clear of people", "Chain is loose for easy starting", "Throttle is fully open", "Bar oil reservoir is empty"], correctOption: 0 },
  { moduleId: 20, order: 2, question: "If the recoil starter cord does not retract after pulling, this most likely indicates:", options: ["The engine is flooded", "A broken or damaged recoil spring", "The chain brake is disengaged", "Low fuel level"], correctOption: 1 },
  { moduleId: 20, order: 3, question: "What is the correct ground-starting position for a chainsaw?", options: ["Hold the saw between your knees with the bar pointing forward", "Balance the saw on the chain brake guard", "Place the rear handle under your right foot, hold the front handle, bar clear of the ground", "Hold the saw by the bar with one hand"], correctOption: 2 },
  { moduleId: 20, order: 4, question: "The chain brake must be engaged during the starting procedure:", options: ["Only after the engine has warmed up", "Never — it prevents the engine from starting", "Only when starting on steep slopes", "At all times throughout the starting procedure"], correctOption: 3 },

  // ─── Module 21: Clutch Assembly ──────────────────────────────────────────────
  { moduleId: 21, order: 1, question: "When does the centrifugal clutch on a chainsaw typically engage the chain?", options: ["At idle speed only", "Immediately on engine start", "At a higher RPM as engine speed increases above idle", "Only when the throttle trigger is fully released"], correctOption: 2 },
  { moduleId: 21, order: 2, question: "A worn clutch drum will most commonly result in:", options: ["The chain running at idle — a serious safety hazard", "Improved chain engagement at lower speeds", "Reduced fuel consumption", "Increased cutting speed"], correctOption: 0 },
  { moduleId: 21, order: 3, question: "What is typically required to safely remove a chainsaw clutch assembly?", options: ["A standard socket set only", "Mole grips on the flywheel", "Only a large screwdriver", "A clutch removal tool with the correct thread direction and a piston stop"], correctOption: 3 },
  { moduleId: 21, order: 4, question: "The clutch springs are responsible for:", options: ["Holding the clutch pads retracted at idle so the chain does not move", "Returning the throttle trigger to idle position", "Tensioning the guide bar", "Driving the oil pump"], correctOption: 0 },

  // ─── Module 22: Sprocket ─────────────────────────────────────────────────────
  { moduleId: 22, order: 1, question: "Why must a worn drive sprocket be replaced?", options: ["To improve the appearance of the saw", "A worn sprocket reduces vibration", "Worn teeth improve chain engagement", "Worn teeth accelerate chain and bar wear and can cause chain derailment"], correctOption: 3 },
  { moduleId: 22, order: 2, question: "When fitting a new chain, what else should always be inspected for wear?", options: ["The drive sprocket, as chain and sprocket wear together", "The air filter", "The spark plug", "The fuel filter"], correctOption: 0 },
  { moduleId: 22, order: 3, question: "What is the maximum recommended sprocket wear before it must be replaced?", options: ["0.1mm", "1.0mm", "0.3mm or as specified by the manufacturer", "2.0mm"], correctOption: 2 },
  { moduleId: 22, order: 4, question: "A rim (spur) sprocket design allows:", options: ["Greater cutting accuracy", "Higher idle speeds", "Direct drive to the chain without a clutch", "The rim to be replaced without replacing the complete clutch drum"], correctOption: 3 },

  // ─── Module 23: Chain Brake ───────────────────────────────────────────────────
  { moduleId: 23, order: 1, question: "The inertia-activated chain brake operates by:", options: ["The operator pressing a dedicated button", "The front hand guard being pressed by the operator's wrist", "A flyweight mechanism detecting rapid saw body rotation and triggering automatically", "Releasing the throttle trigger"], correctOption: 2 },
  { moduleId: 23, order: 2, question: "How should the chain brake be tested before beginning work?", options: ["Rev to full throttle and deliberately trigger kickback", "Check it in the workshop with the bar removed", "It does not require testing before use", "At low revs, push the front guard forward with the wrist — the chain must stop instantly"], correctOption: 3 },
  { moduleId: 23, order: 3, question: "If the chain continues rotating when the chain brake is activated, you must:", options: ["Stop work immediately — do not use the saw until the brake is repaired", "Continue working but exercise extra care", "Increase the engine idle speed", "Tighten the guide bar nuts"], correctOption: 0 },
  { moduleId: 23, order: 4, question: "Kickback is most likely to occur when:", options: ["Crosscutting with the bottom of the bar through clear timber", "Cutting slowly at low chain speed", "Refuelling the saw in the field", "The tip (nose) of the bar contacts a solid object or the chain is pinched"], correctOption: 3 },

  // ─── Module 24: Guidebar ─────────────────────────────────────────────────────
  { moduleId: 24, order: 1, question: "Why should the guide bar be regularly rotated 180 degrees?", options: ["To improve chain speed", "To change the cutting direction", "To allow even wear on both sides of the bar rail", "To clear the bar oil feed holes"], correctOption: 2 },
  { moduleId: 24, order: 2, question: "What should be checked in the guide bar groove during inspection?", options: ["Fuel tank level", "Bar length only", "Drive link count", "Groove depth, rail burrs, and bar oil holes for blockage"], correctOption: 3 },
  { moduleId: 24, order: 3, question: "A guide bar with a peened (closed or damaged) rail groove causes:", options: ["Reduced chain lubrication and premature bar and chain wear", "Improved cutting accuracy", "Faster chain speed", "Reduced vibration"], correctOption: 0 },
  { moduleId: 24, order: 4, question: "Bar oil feed holes must be kept clear to ensure:", options: ["Correct chain tension is maintained", "Correct chain brake function", "Adequate lubrication of the chain and bar throughout cutting", "Engine cooling airflow"], correctOption: 2 },

  // ─── Module 25: Chain Basics ─────────────────────────────────────────────────
  { moduleId: 25, order: 1, question: "Drive links on a chainsaw chain serve to:", options: ["Cut through the wood", "Reduce vibration transmission", "Measure the chain length", "Engage with the drive sprocket and guide bar groove to drive and guide the chain"], correctOption: 3 },
  { moduleId: 25, order: 2, question: "The pitch of a chainsaw chain is defined as:", options: ["The average distance between chain links (every other rivet distance divided by two)", "The angle of the cutter teeth", "The depth gauge height", "The overall chain width"], correctOption: 0 },
  { moduleId: 25, order: 3, question: "The depth gauge (raker) on a chain cutter controls:", options: ["Chain speed", "Chain tension", "The depth of cut each cutter tooth takes into the wood", "Bar lubrication flow"], correctOption: 2 },
  { moduleId: 25, order: 4, question: "Which part of the chainsaw chain actually cuts the wood?", options: ["The tie straps", "The drive links", "The left and right cutter teeth", "The bumper drive links"], correctOption: 2 },

  // ─── Module 26: Chain Tension ────────────────────────────────────────────────
  { moduleId: 26, order: 1, question: "How is correct chain tension identified on a standard chainsaw?", options: ["The chain hangs loosely below the bar", "The chain cannot be moved by hand at all", "The chain pulls slightly away from the bar but snaps back with drive links remaining in the groove", "Pliers are needed to move the chain along the bar"], correctOption: 2 },
  { moduleId: 26, order: 2, question: "Why is operating with a chain that is too loose dangerous?", options: ["It reduces fuel consumption", "It improves cutting performance", "It reduces operating noise", "A loose chain can derail from the bar, creating a serious injury risk"], correctOption: 3 },
  { moduleId: 26, order: 3, question: "When should chain tension be checked?", options: ["Before use and at regular intervals — new chains need especially frequent re-tensioning", "Only at the start of the working day", "Only when the chain appears loose", "Once per week only"], correctOption: 0 },
  { moduleId: 26, order: 4, question: "A chain that is too tight will cause:", options: ["Improved cutting speed", "Excessive wear on bar, chain, and sprocket, and potentially dangerous bar heating", "Reduced kickback risk", "Better lubrication distribution"], correctOption: 1 },

  // ─── Module 27: Identifying The Chain ───────────────────────────────────────
  { moduleId: 27, order: 1, question: "What three measurements correctly identify a replacement chainsaw chain?", options: ["Bar length, engine displacement, and bar width", "Chain age, colour, and manufacturer name", "Pitch, gauge (drive link thickness), and number of drive links", "Cutter height, depth gauge setting, and chain weight"], correctOption: 2 },
  { moduleId: 27, order: 2, question: "The gauge of a chainsaw chain refers to:", options: ["The number of cutting teeth", "The cutting angle of the teeth", "The chain's total length", "The thickness of the drive links that fit into the guide bar groove"], correctOption: 3 },
  { moduleId: 27, order: 3, question: "Common professional chainsaw chain pitches include:", options: [".325, 3/8, and .404 inch", "1/4, 1/2, and 3/4 inch", ".325, 3/8, and 1/4 inch (for lightweight saws)", "Only 3/8 inch is used professionally"], correctOption: 0 },
  { moduleId: 27, order: 4, question: "If an incorrect gauge chain is fitted to a guide bar:", options: ["Cutting performance will improve", "There will be no noticeable difference", "The chain may bind or rattle in the groove, leading to accelerated wear or derailment", "Chain speed will increase"], correctOption: 2 },

  // ─── Module 28: Replacing The Chain ─────────────────────────────────────────
  { moduleId: 28, order: 1, question: "Before removing or fitting a chainsaw chain, what must always be done first?", options: ["Rev the engine to full speed to slacken the chain", "Remove the guide bar first", "Only engage the chain brake — engine can remain running", "Stop the engine, disconnect the spark plug lead, and engage the chain brake"], correctOption: 3 },
  { moduleId: 28, order: 2, question: "When fitting a new chain, which direction must the cutting teeth face on the top of the bar?", options: ["Facing forwards towards the bar nose", "Facing backwards towards the engine", "Alternating forwards and backwards", "Direction does not matter"], correctOption: 0 },
  { moduleId: 28, order: 3, question: "After fitting a new chain, before starting the engine you must:", options: ["Run the saw for 5 minutes with the chain stationary", "Manually oil the chain for 10 minutes", "Confirm drive links are in the groove, check tension, and re-fit the bar cover", "Adjust the carburettor idle speed"], correctOption: 2 },
  { moduleId: 28, order: 4, question: "Why do new chains require more frequent tension checks initially?", options: ["New chains are harder and expand with heat", "New chains are thinner and more elastic", "New chains run faster and wear the bar quickly", "New chains stretch as components bed in during initial use"], correctOption: 3 },

  // ─── Module 29: Chain Sharpening ────────────────────────────────────────────
  { moduleId: 29, order: 1, question: "When sharpening a cutter, the file should be held at:", options: ["The manufacturer-specified horizontal angle (typically 25-35 degrees)", "90 degrees straight across the chain", "45 degrees downward into the cutter", "Parallel to the guide bar"], correctOption: 0 },
  { moduleId: 29, order: 2, question: "The depth gauge (raker) on a chain cutter:", options: ["Guides the file during sharpening", "Measures chain tension directly", "Indicates when the chain needs full replacement", "Limits how deeply each cutter bites into the wood, controlling chip thickness"], correctOption: 3 },
  { moduleId: 29, order: 3, question: "If depth gauges become too high relative to the cutters after repeated sharpening:", options: ["The chain cuts more aggressively", "Chain speed increases significantly", "The chain cuts poorly because the cutters cannot engage the wood adequately", "There is no effect on cutting performance"], correctOption: 2 },
  { moduleId: 29, order: 4, question: "After sharpening, all cutters on the chain must be:", options: ["Different lengths to compensate for uneven wood hardness", "The same length and sharpened to the same angle for smooth, efficient cutting", "Longer on one side than the other", "Set to varying depth gauge heights"], correctOption: 1 },

  // ─── Module 30: Stacking ─────────────────────────────────────────────────────
  { moduleId: 30, order: 1, question: "What is the maximum recommended height for a freestanding timber stack without additional support?", options: ["1.0 metre", "3.0 metres", "There is no recommended maximum height", "As specified in the site risk assessment (typically 1.5m)"], correctOption: 3 },
  { moduleId: 30, order: 2, question: "Cross-stacking the top layer of a timber stack is done to:", options: ["Improve stability and prevent the stack rolling or collapsing", "Make log counting easier", "Allow faster timber drying", "Mark the stack for collection"], correctOption: 0 },
  { moduleId: 30, order: 3, question: "The stacking work area should be:", options: ["Uneven ground to give better grip to stacked timber", "As close to felling operations as possible regardless of slope", "On stable, clear ground away from slope run-out zones", "Directly beside any active felling work"], correctOption: 2 },
  { moduleId: 30, order: 4, question: "Before approaching an existing timber stack for further work, you must:", options: ["Approach quickly to check for hazards", "Place additional timber on top to test stability", "Ignore the stack and focus on other nearby work", "Visually assess the stack for signs of instability before approaching"], correctOption: 3 },

  // ─── Module 31: Work Positioning ────────────────────────────────────────────
  { moduleId: 31, order: 1, question: "The recommended cutting stance for cross-cutting timber is:", options: ["Feet together, facing the cut directly", "Kneeling beside the log", "Balanced stance with feet shoulder-width apart, good footing, body weight evenly distributed", "Standing directly over the log"], correctOption: 2 },
  { moduleId: 31, order: 2, question: "Why must the operator never stand directly in line with the bar when cross-cutting?", options: ["It reduces cutting efficiency", "It is harder to see the cut line accurately", "It increases vibration exposure to the legs", "In the event of kickback, the bar swings toward the operator's face and upper body"], correctOption: 3 },
  { moduleId: 31, order: 3, question: "When should the operator plan and check their escape route?", options: ["Before starting any cut", "After the cut is completed", "Only when working on steep slopes", "Only when working in proximity to other people"], correctOption: 0 },
  { moduleId: 31, order: 4, question: "What is the minimum safe working distance between two operators using chainsaws simultaneously?", options: ["2 metres", "5 metres", "At least two tree lengths apart (minimum 50 metres on most sites)", "10 metres"], correctOption: 2 },

  // ─── Module 32: Pre-Start Checks ────────────────────────────────────────────
  { moduleId: 32, order: 1, question: "Which of the following is NOT typically part of a pre-start chainsaw check?", options: ["Checking fuel and bar oil levels", "Inspecting chain brake function", "Adjusting the carburettor idle speed", "Checking chain tension and sharpness"], correctOption: 2 },
  { moduleId: 32, order: 2, question: "If fuel is leaking from the saw during a pre-start check, you should:", options: ["Stop — do not start the saw and arrange repair before use", "Continue but check it again at lunch", "Use the saw quickly before the leak worsens", "Wipe the fuel away and proceed normally"], correctOption: 0 },
  { moduleId: 32, order: 3, question: "Pre-start checks should be carried out:", options: ["Once per week", "Only when the operator changes", "Before each work session and after the saw has been left unattended", "Only at the start of a new contract"], correctOption: 2 },
  { moduleId: 32, order: 4, question: "During a pre-start chain inspection, you are checking for:", options: ["Number of cutting teeth only", "Chain colour and manufacturer markings", "Chain speed at idle", "Sharpness, correct tension, drive links in groove, and no damaged links"], correctOption: 3 },

  // ─── Module 33: Starting The Chainsaw ───────────────────────────────────────
  { moduleId: 33, order: 1, question: "Why must the chain brake be engaged before starting a chainsaw?", options: ["It is not necessary to engage the brake for starting", "To increase compression for easier starting", "To warm the engine before operational use", "To prevent chain rotation during the starting procedure, reducing injury risk"], correctOption: 3 },
  { moduleId: 33, order: 2, question: "The correct ground-starting position for a chainsaw is:", options: ["Place rear handle under right foot, hold front handle with bar clear of ground", "Hold front handle, place saw between the knees", "Hang saw by the front guard and pull cord upward", "Start with the bar held vertically"], correctOption: 0 },
  { moduleId: 33, order: 3, question: "A flooded chainsaw engine is typically caused by:", options: ["Too little fuel reaching the engine", "A blocked air filter", "Excess fuel in the engine from incorrect choke or throttle use during starting", "Low engine compression"], correctOption: 2 },
  { moduleId: 33, order: 4, question: "After starting a cold engine, why must the choke be returned to the run position?", options: ["The choke improves fuel efficiency during warm-up", "Leaving the choke on causes an over-rich mixture that stalls or damages the engine", "The choke controls chain speed at idle", "The choke only affects the initial starting phase"], correctOption: 1 },

  // ─── Module 34: Pre-Use Checks ──────────────────────────────────────────────
  { moduleId: 34, order: 1, question: "The throttle trigger interlock must be confirmed to:", options: ["Open the throttle smoothly when fully pressed", "Rev the engine to maximum speed", "Prevent throttle engagement unless the interlock is simultaneously depressed", "Allow the chain to move at idle speed"], correctOption: 2 },
  { moduleId: 34, order: 2, question: "How is bar oil reaching the chain confirmed during a pre-use check?", options: ["Confirm the bar oil reservoir is completely empty before refilling", "Remove the oil cap during operation to observe flow", "Run the chain dry for the first 10 minutes and then check", "Hold saw over light-coloured material and check for oil spray while revving"], correctOption: 3 },
  { moduleId: 34, order: 3, question: "A pre-use check of the guide bar should confirm:", options: ["No visible cracks, even undamaged rails, and a freely rotating sprocket nose", "The bar is the correct manufacturer colour", "The bar is at least 40cm in length", "The bar is clean and has been freshly painted"], correctOption: 0 },
  { moduleId: 34, order: 4, question: "If the chain brake does NOT stop the chain when tested during a pre-use check, you must:", options: ["Continue working but remain extra vigilant", "Tighten the guide bar nuts and retest", "Take the saw out of service immediately and arrange for repair", "Engage the brake manually with your hand as a workaround"], correctOption: 2 },

  // ─── Module 35: Cutting Basics ───────────────────────────────────────────────
  { moduleId: 35, order: 1, question: "Feed rate when cross-cutting timber refers to:", options: ["The speed at which the operator walks between cutting positions", "The rate at which the chain is sharpened in the field", "The speed at which the bar is guided through the timber during the cut", "Engine RPM maintained during cutting"], correctOption: 2 },
  { moduleId: 35, order: 2, question: "During a cross-cut, the engine should be at:", options: ["Idle speed to reduce kickback risk", "Half throttle for improved control", "Whatever speed the operator prefers", "Full throttle throughout the entire cut"], correctOption: 3 },
  { moduleId: 35, order: 3, question: "What is the purpose of the bumper spikes (felling dogs) during cross-cutting?", options: ["Act as a pivot point against the timber for better control and leverage", "Mark the timber for cutting", "Protect the bar nose from damage", "Assist in sharpening the cutting teeth"], correctOption: 0 },
  { moduleId: 35, order: 4, question: "When should the throttle be released after completing a cross-cut?", options: ["Before the chain contacts the wood", "Immediately as the cut finishes while the bar is still in the wood", "After the cut is complete and the bar is clear of the timber", "Never — full throttle must be maintained throughout"], correctOption: 2 },

  // ─── Module 36: Tension & Compression ───────────────────────────────────────
  { moduleId: 36, order: 1, question: "When a log is in compression on its upper face (supported at both ends), the safe cutting technique is:", options: ["Underbuck (cut upward from below) first, then finish from the top", "Cut straight through from the top in a single overbuck pass", "Cut from the end of the log inward", "Do not attempt to cut logs in compression"], correctOption: 0 },
  { moduleId: 36, order: 2, question: "When a log is in tension on its upper face (cantilevered, supported one end), the safe technique is:", options: ["Underbuck in a single pass", "Overbuck first to prevent pinching, then finish from below", "Cut through the middle of the log in one pass", "Always cut from the side to avoid all risk"], correctOption: 1 },
  { moduleId: 36, order: 3, question: "If a bar becomes pinched in a compression cut, what is the likely outcome?", options: ["The chain cuts faster to free itself", "The chain brake activates automatically", "The saw will safely shut down", "The wood grips the bar, potentially stalling the saw or causing loss of control"], correctOption: 3 },
  { moduleId: 36, order: 4, question: "Before any cross-cut, the operator must assess:", options: ["Where tension and compression zones are to determine the safe cutting sequence", "The colour and species of the timber only", "Only whether the timber is wet or dry", "Only the diameter of the timber"], correctOption: 0 },

  // ─── Module 37: Releasing A Trapped Chainsaw ────────────────────────────────
  { moduleId: 37, order: 1, question: "If the chainsaw bar becomes pinched during a cut, the FIRST action is:", options: ["Pull the saw repeatedly until it comes free", "Rev the engine to maximum to force the bar free", "Remove the chain from the bar while it remains pinched", "Release the throttle and assess the situation calmly before attempting to free the bar"], correctOption: 3 },
  { moduleId: 37, order: 2, question: "A safe method to release a pinched bar without power tools is:", options: ["Lever the kerf open using a wedge or felling lever inserted into the cut", "Strike the log firmly with the chainsaw body", "Cut from a completely different direction at full speed without further assessment", "Stand on the log and pull the saw upward with both hands"], correctOption: 0 },
  { moduleId: 37, order: 3, question: "When using a felling wedge to release a trapped bar, it should be inserted:", options: ["Into the kerf on the compression side to open the cut", "Into the kerf on the tension side", "Using the chainsaw bar itself to drive the wedge in", "While the chain is still running at full speed"], correctOption: 0 },
  { moduleId: 37, order: 4, question: "If the engine stalls while the bar is pinched in timber, you should:", options: ["Restart the engine immediately and force the cut through", "Use bare hands to manually open the kerf", "Make the saw safe and use hand tools or a second saw to release it safely", "Leave the saw in the timber and continue other work"], correctOption: 2 },

  // ─── Module 38: Bore Cutting ─────────────────────────────────────────────────
  { moduleId: 38, order: 1, question: "Bore cutting is performed using:", options: ["The top of the bar in a controlled downward motion", "The full length of the bar in a rapid thrust", "The lower part of the bar nose, entering the wood to minimise kickback risk", "The chain at idle speed only"], correctOption: 2 },
  { moduleId: 38, order: 2, question: "Why is bore cutting considered a higher-risk technique?", options: ["It consumes significantly more fuel", "It requires a longer bar than standard cross-cutting", "It is only a risk in wet or icy conditions", "It uses the bar nose area where kickback is most likely to be initiated"], correctOption: 3 },
  { moduleId: 38, order: 3, question: "Before performing a bore cut, the operator must:", options: ["Assess wood tension and compression and confirm a clear escape route", "Loosen the chain for greater flexibility", "Set the engine to idle speed for safety", "Ensure the bar is shorter than 35cm"], correctOption: 0 },
  { moduleId: 38, order: 4, question: "Bore cutting is most commonly used for:", options: ["Routine cross-cutting of felled timber", "Sharpening the chain in the field", "Sectional felling, sink cuts, and precision felling in confined spaces", "Felling trees with a diameter greater than bar length"], correctOption: 2 },

  // ─── Module 39: Oversized & Tensioned Timber ─────────────────────────────────
  { moduleId: 39, order: 1, question: "When timber diameter exceeds the guide bar length, the correct cross-cutting technique is:", options: ["Fit a longer bar before attempting the cut", "Cut at an angle to reach the centre of the log", "Do not attempt — the timber cannot be safely cut", "Cut from one side, then reposition and cut from the opposite side"], correctOption: 3 },
  { moduleId: 39, order: 2, question: "The key additional hazard when working with large diameter timber is:", options: ["Roll hazard — large logs can roll unexpectedly during or after cutting", "The increased weight of the chainsaw", "Increased noise levels from the larger log", "Excessive sawdust production"], correctOption: 0 },
  { moduleId: 39, order: 3, question: "Tensioned timber creates a specific risk of:", options: ["The wood burning during the cutting process", "The chain becoming magnetised", "Sudden and unpredictable movement of log sections endangering the operator", "Fuel contamination from the timber"], correctOption: 2 },
  { moduleId: 39, order: 4, question: "Before cutting oversized or tensioned timber, the operator must:", options: ["Thoroughly assess the timber, identify tension/compression zones, plan all cuts, and confirm escape route", "Begin cutting immediately to release the tension safely", "Ask a bystander to watch from a safe distance", "Wait 10 minutes after the timber has come to rest before cutting"], correctOption: 0 },
];

async function main() {
  console.log(`Inserting ${questions.length} quiz questions for 30 video modules...`);
  for (const q of questions) {
    await db.insert(quizQuestionsTable).values({
      moduleId: q.moduleId,
      question: q.question,
      options: JSON.stringify(q.options),
      correctOption: q.correctOption,
      order: q.order,
    });
  }
  console.log("Done.");
  process.exit(0);
}

main().catch((err) => { console.error(err); process.exit(1); });
